### ISSUE TITLE
2Captcha

### ISSUE THREAD

**Issue by alphanumericaltycoon** [hendrikbgr/YandexMail-Account-Creator#55]
Hi.

OS: Kali Linux

I just wanted to confirm that I'm right in thinking that this script requires you to first add funds to 2captcha in order to work? Or is there a free version that I'm missing.

I ran the code and it appeared to be running fine except it couldn't get through the captcha.. I'm  guessing because my account does not have.

I'd be grateful for the clarification. Thanks.

Terminal output:
```

┌──(kali㉿kali)-[~/YandexMail-Account-Creator]
└─$ python3 creator.py                                                                                            1 ⨯

    __  ___      _ __
   /  |/  /___ _(_) /
  / /|_/ / __ `/ / /
 / /  / / /_/ / / /
/_/  /_/\__,_/_/_/

    ___                               __
   /   | ______________  __  ______  / /_
  / /| |/ ___/ ___/ __ \/ / / / __ \/ __/
 / ___ / /__/ /__/ /_/ / /_/ / / / / /_
/_/  |_\___/\___/\____/\__,_/_/ /_/\__/

   ______                __
  / ____/_______  ____ _/ /_____  _____
 / /   / ___/ _ \/ __ `/ __/ __ \/ ___/
/ /___/ /  /  __/ /_/ / /_/ /_/ / /
\____/_/   \___/\__,_/\__/\____/_/

Auto Account Creator Script
Getting Chrome driver...
Proxy: PROXYADDRESSHERE:PROXYPASSWORD
ERROR_ZERO_BALANCE
No Recapchta possible...
Trying next proxy...
Traceback (most recent call last):
  File "/home/kali/YandexMail-Account-Creator/creator.py", line 283, in <module>
    wait.until(EC.element_to_be_clickable(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/support/expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id

                                                                                                                      
┌──(kali㉿kali)-[~/YandexMail-Account-Creator]
└─$       

```

**Comment by hendrikbgr** [comment]
Hello, yes you do need in fact funds on your 2captcha account. 3USD is enough to create 3k accounts. Sadly there is no free trial for this.
