### ISSUE TITLE
Captcha Click Error

### ISSUE THREAD

**Issue by FeelsBadMan1** [hendrikbgr/YandexMail-Account-Creator#57]
Hello, i ran the script and the fist things worked fine. However at the point where it tried to solve the given captcha this error happend. im using WIndows:
```
Traceback (most recent call last):
  File "D:\downloaded pythonprojects\YandexMail-Account-Creator-master\creator.py", line 222, in <module>
    wait.until(EC.element_to_be_clickable(
  File "D:\Downloads\Python\python 3.9.6\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "D:\Downloads\Python\python 3.9.6\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "D:\Downloads\Python\python 3.9.6\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Downloads\Python\python 3.9.6\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="captcha__reload" role="button" tabindex="0">...</div> is not clickable at point (838, 803). Other element would receive the click: <table data-id="table" class="sc-dlnjPT cuIYFB">...</table>
  (Session info: chrome=92.0.4515.131)
  ```

**Comment by hendrikbgr** [comment]
This issue got fixed with the last update (git pull or redownload)
