### ISSUE TITLE
Click error

### ISSUE THREAD

**Issue by jhemmmm** [hendrikbgr/YandexMail-Account-Creator#60]
```
Great! We added you account details to the table.
Traceback (most recent call last):
  File "creator.py", line 293, in <module>
    (By.XPATH, '/html/body/div/div/div[2]/div[1]/div/div/div/a[1]/div'))).click()
  File "D:\laragon\bin\python\python-3.6.1\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by rich1488** [comment]
im having the same issue, it doesnt start on the next one after first one is created.

did you find a fix for this?
