### ISSUE TITLE
Chromedriver no permission

### ISSUE THREAD

**Issue by Yoko11111111** [hendrikbgr/YandexMail-Account-Creator#69]
Hello the browser closes instantly bc the chromedriver has no permission? My own Selenium project works fine and no problems with chromedriver

**Comment by hendrikbgr** [comment]
hello, have you got the correct version of the chromedriver? it must be the same version as your regular chrome browser. Also can you please add the error code here.

**Comment by Yoko11111111** [comment]
Im using the chromedriver that is in the folder.

**Comment by Yoko11111111** [comment]
Traceback (most recent call last):
  File "C:\Users\jamu\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\jamu\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\jamu\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Zugriff verweigert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jamu\OneDrive\Desktop\YandexMail-Account-Creator\creator.py", line 120, in <module>
    driver = uc.Chrome(options=options)
  File "C:\Users\jamu\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\jamu\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\jamu\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\jamu\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: '41cb849134a2f786_chromedriver.exe' executable may have wrong permissions. Please see https://chromedriver.chromium.org/home

**Comment by hendrikbgr** [comment]
What OS are you using? Windows?

**Comment by Yoko11111111** [comment]
yes

**Comment by hendrikbgr** [comment]
try downloading a fresh version of chromedriver form here please and replace what ever you have in the folder now and make sure its called chromedriver.exe

**Comment by hendrikbgr** [comment]
also execute the chromedriver.exe once before running the script to ensure your system has the right permissions to execute that exe file

**Comment by hendrikbgr** [comment]
https://stackoverflow.com/questions/49787327/selenium-on-mac-message-chromedriver-executable-may-have-wrong-permissions

**Comment by hendrikbgr** [comment]
also for more support you can join my discord server: https://discord.gg/HF6V6Vq2MV
